name: Generate json file and push to frontend

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [new_commit]

jobs:
  gen_json_n_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout source repo (cofi)
      uses: actions/checkout@v2
      with:
        repository: 'inlab-geo/cofi'
        path: 'cofi'
    
    - name: Copy files to search engine (cofi)
      run: |
        cp -R cofi/. pysearch_tool/cofi

    - name: Checkout source repo (espresso)
      uses: actions/checkout@v2
      with:
        repository: 'inlab-geo/espresso'
        path: 'espresso'
    
    - name: Copy files to search engine (espresso)
      run: |
        cp -R espresso/. pysearch_tool/espresso

    - name: Checkout source repo (cofi-examples)
      uses: actions/checkout@v2
      with:
        repository: 'inlab-geo/cofi-examples'
        path: 'cofi-examples'
    
    - name: Copy files to search engine (cofi-examples)
      run: |
        cp -R cofi-examples/. pysearch_tool/cofi-examples

    - name: Checkout target repo
      uses: actions/checkout@v2
      with:
        repository: 'inlab-geo/inlab-explorer'
        path: 'target-repo'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run the script and generate JSON files
      run: |
        python main.py  # Modify this if your script is in a different location

    - name: Move generated JSON files to target repo
      run: |
        mv *.json target-repo/public 
        
    - name: Check for changes
      run: |
        cd target-repo
        git add .
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "changes_detected=true"
          echo "changes_detected=true" >> $GITHUB_ENV
          git config --global user.name "jwhhh"
          git config --global user.email "hanghur@gmail.com"
        else
          echo "changes_detected=false"
          echo "changes_detected=false" >> $GITHUB_ENV
        fi
  
    - name: Pushes to another repository
      id: push_directory
      if: env.changes_detected == 'true'
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        source-directory: target-repo/
        destination-github-username: 'inlab-geo'
        destination-repository-name: 'inlab-explorer'
        user-name: jwhhh
        user-email: hanghur@gmail.com
        commit-message: "chore: update JSON files from ORIGIN_COMMIT"
        target-branch: main
